# latexmk configuration for Scaffold-ChunGS thesis
# 中国地质大学（武汉）学士学位论文
# xelatex (ctex Chinese) + biber (GB/T 7714-2005)
$pdf_mode = 1;
$xelatex = "xelatex -synctex=1 -interaction=nonstopmode %O %S";
$bibtex = "biber %O %B";
$clean_ext = "bbl bcf blg run.xml auxlock thm loa lot lof toc out";
$max_repeat = 4;
